### ISSUE TITLE
Typescript, array of parameters for an Atomic Transaction without any type assigned

### ISSUE THREAD

**Issue by BubsLB** [scale-it/algo-builder#409] opened 2021-07-09 08:33 UTC
## Describe the bug
Hello,
I'm using typescript for create a script, and if I'm going to declare an array of parameters for an Atomic Transaction, so composed by heterogeneous types I need to specify _any_ as type for the array, if I don't specify anything, it returns the following error.

<img width="1661" alt="Schermata 2021-07-09 alle 10 01 45" src="https://user-images.githubusercontent.com/74781915/125049007-c9cd5b80-e0a0-11eb-921e-83f9cc977d37.png">

#### Expected Behavior
Should works without any type assigned

## Steps to Reproduce

1. 
2. 

### Environment

- OS: iOS 11.4
- Node.js version: 14.17.0
- algob version: 1.1.0

**Comment by amityadav0** [comment] 2021-07-09 13:40
Hi
could you please try with `const atomicTransaction: rtypes.ExecParams[]` type ?
you can import it using `import { rtypes } from '@algorand-builder/runtime';`.

https://algobuilder.dev/api/runtime/modules/types.html

**Comment by BubsLB** [comment] 2021-07-09 13:54
> Hi
> could you please try with `const atomicTransaction: rtypes.ExecParams[]` type ?
> you can import it using `import { rtypes } from '@algorand-builder/runtime';`.
> 
> https://algobuilder.dev/api/runtime/modules/types.html

Hi, now it works, but I've another problem on changing the "fromAccount" in the lines below, because the property fromAccount doesn't exist in ExecParams. I changed it in 'fromAccountAddr = bob.addr;'

<img width="1768" alt="Schermata 2021-07-09 alle 15 46 42" src="https://user-images.githubusercontent.com/74781915/125088307-948b3280-e0cd-11eb-90a1-2183c411cbf3.png">

<img width="629" alt="Schermata 2021-07-09 alle 15 48 30" src="https://user-images.githubusercontent.com/74781915/125088430-ae2c7a00-e0cd-11eb-8f49-9a1448eeac65.png">



Is it correct ?

**Comment by amityadav0** [comment] 2021-07-09 14:13
yes, you are right. you should be able to change using `fromAccount`. checking the cause

**Comment by robert-zaremba** [comment] 2021-07-16 08:24
The fix is backported to `master` and released in [v1.1.2](https://github.com/scale-it/algo-builder/releases/tag/v1.1.2).

**Closed by robert-zaremba** 2021-07-16 08:24 UTC
Labels: bug
