### ISSUE TITLE
DAO Example: Transaction Failed when using execute.js script

### ISSUE THREAD

**Issue by icaparros-at-wiris** [scale-it/algo-builder#555] opened 2022-01-22 00:47 UTC
I am trying to test the DAO example and all scripts seems to work correctly. But when I use the execute.js script using this command line.

```
yarn run algob run scripts/run/execute.js
```

I receive a Transaction Failed Error with the status code 400.

```
Transaction Failed Error: cannot POST /ps2/v2/transactions (400)
    at Response.toError (/home/isaac/Downloads/my_new_project/dao/node_modules/superagent/src/node/response.js:95:15)
    at Response._setStatusProperties (/home/isaac/Downloads/my_new_project/dao/node_modules/superagent/src/response-base.js:126:48)
    at new Response (/home/isaac/Downloads/my_new_project/dao/node_modules/superagent/src/node/response.js:41:8)
    at Request._emitResponse (/home/isaac/Downloads/my_new_project/dao/node_modules/superagent/src/node/index.js:928:20)
    at fn (/home/isaac/Downloads/my_new_project/dao/node_modules/superagent/src/node/index.js:1130:38)
    at IncomingMessage.<anonymous> (/home/isaac/Downloads/my_new_project/dao/node_modules/superagent/src/node/parsers/image.js:8:5)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 400,
  text: undefined,
  method: 'POST',
  path: '/ps2/v2/transactions'
}
```

I follow all the commands from https://github.com/scale-it/algo-builder/tree/master/examples/dao in the same order.

Thank you!

**Comment by vuvth** [comment] 2022-01-25 16:06
Hi @icaparros-at-wiris! 

The problem is we use LatestTimestamp to compare the time. So if we don't commit any block, [LastTimestamp](https://developer.algorand.org/docs/get-details/dapps/avm/teal/opcodes/?from_query=LatestTimestamp#global-f). It's not changed on sandbox or private network if you not commit any block to network.
We can only run execute.js success when the proposal is complete voting period and before the execute_before moment.

**Comment by robert-zaremba** [comment] 2022-01-25 19:44
@icaparros-at-wiris  if you try our runtime and tests then you should see more descriptive errors.

**Comment by icaparros-at-wiris** [comment] 2022-01-26 07:59
@vuvth, I tested that and i works correctly. I didn't realize that it should be executed before `execute_before` (it make sense).
 
 Thank you.

**Comment by vuvth** [comment] 2022-01-26 08:30
We are glad to help you, @icaparros-at-wiris!
If don't have any problem please close this issue.

**Closed** 2022-01-26 15:23 UTC

**Comment by robert-zaremba** [comment] 2022-01-27 11:03
NOTE: we are using the `--dev` mode - so the blocks are produced on "demand" only.
